'use client';
import {useEffect,useState} from 'react'; import {Shield,KeyRound,Users,Activity,Plus,Trash2,Power,RefreshCw} from 'lucide-react';
export default function Admin(){const [keys,setKeys]=useState<any[]>([]);const[users,setUsers]=useState<any[]>([]);const[err,setErr]=useState('');const[label,setLabel]=useState('');const[secret,setSecret]=useState('');const[msg,setMsg]=useState('');
async function load(){const [k,u]=await Promise.all([fetch('/api/admin/keys'),fetch('/api/admin/users')]);const kd=await k.json();const ud=await u.json();if(k.ok)setKeys(kd.keys||[]);else setErr(kd.error||'Admin access required');if(u.ok)setUsers(ud.users||[])} useEffect(()=>{load()},[]);
async function add(){setMsg('');const r=await fetch('/api/admin/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label,secret})});const d=await r.json();if(!r.ok){setMsg(d.error||'Failed');return}setLabel('');setSecret('');setMsg('API key added securely.');load()}
async function toggle(k:any){await fetch('/api/admin/keys',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:k.id,enabled:!k.enabled})});load()}
async function test(k:any){setMsg('Testing…');const r=await fetch('/api/admin/keys/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:k.id})});const d=await r.json();setMsg(r.ok&&d.ok?'Key is healthy.':d.error||`Key test failed (${d.status||''})`);load()}
async function remove(k:any){if(!confirm(`Delete ${k.label}?`))return;await fetch(`/api/admin/keys?id=${k.id}`,{method:'DELETE'});load()}
return <main className="mx-auto max-w-6xl px-6 py-10"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-violet-300"><Shield size={20}/>Admin Console</div><h1 className="mt-2 text-3xl font-semibold">Operations Dashboard</h1><p className="mt-2 text-sm text-white/45">API keys, users and usage controls.</p></div><button onClick={load} className="rounded-xl border border-white/10 p-3"><RefreshCw size={16}/></button></div>{err&&<div className="mt-6 rounded-xl bg-red-500/10 p-4 text-sm text-red-200">{err}</div>}
<div className="mt-8 grid gap-4 md:grid-cols-3"><Stat icon={<KeyRound/>} label="API keys" value={keys.length}/><Stat icon={<Users/>} label="Users" value={users.length}/><Stat icon={<Activity/>} label="Enabled keys" value={keys.filter(k=>k.enabled).length}/></div>
<section className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-semibold">Add API key</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto]"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Label e.g. OpenAI #1" className="rounded-xl border border-white/10 bg-black/20 p-3"/><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="API key (stored encrypted)" className="rounded-xl border border-white/10 bg-black/20 p-3"/><button onClick={add} className="flex items-center justify-center gap-2 rounded-xl bg-violet-500 px-5"><Plus size={16}/>Add</button></div>{msg&&<p className="mt-3 text-xs text-white/50">{msg}</p>}</section>
<section className="mt-6 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-semibold">API Key Manager</h2><div className="mt-4 space-y-3">{keys.map(k=><div key={k.id} className="grid gap-3 rounded-xl border border-white/10 p-4 md:grid-cols-[1fr_auto_auto_auto_auto]"><div><div className="font-medium">{k.label}</div><div className="mt-1 text-xs text-white/35">{k.status} · failures {k.failure_count} · {k.enabled?'enabled':'disabled'}</div></div><button onClick={()=>test(k)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Test</button><button onClick={()=>toggle(k)} className="rounded-lg border border-white/10 px-3 py-2 text-xs"><Power size={14}/></button><button onClick={()=>remove(k)} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-200"><Trash2 size={14}/></button></div>)}{!keys.length&&<p className="text-sm text-white/35">No database-managed keys yet.</p>}</div></section>
<section className="mt-6 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-semibold">Users</h2><div className="mt-4 overflow-auto"><table className="w-full text-left text-xs"><thead className="text-white/35"><tr><th className="p-2">User</th><th className="p-2">Plan</th><th className="p-2">Credits</th><th className="p-2">Used</th><th className="p-2">Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/5"><td className="p-2">{u.display_name||u.id.slice(0,8)}</td><td className="p-2">{u.plan}</td><td className="p-2">{u.credits}</td><td className="p-2">{u.credits_used}</td><td className="p-2">{u.role}</td></tr>)}</tbody></table></div></section></main>}
function Stat({icon,label,value}:{icon:any;label:string;value:any}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="text-white/45">{icon}</div><div className="mt-3 text-2xl font-semibold">{value}</div><div className="text-xs text-white/35">{label}</div></div>}
