'use client';
import {useEffect,useRef,useState} from 'react';
import {UploadCloud,X,Plus,Minus,Sparkles,Copy,Check,BarChart3,Layers3,Download,Loader2,AlertCircle,History,Save} from 'lucide-react';
import type {AnalysisResult} from '@/lib/types';

type Item={id:string;file:File;url:string};
type Trend={imageCount:number;themes:any[];styles:any[];colors:any[];compositions:any[];moods:any[];opportunities:string[]};

export default function Home(){
 const ref=useRef<HTMLInputElement>(null); const[imgs,setImgs]=useState<Item[]>([]); const[level,setLevel]=useState('High'); const[count,setCount]=useState(3); const[target,setTarget]=useState('ChatGPT Image'); const[msg,setMsg]=useState(''); const[copied,setCopied]=useState(false); const[results,setResults]=useState<AnalysisResult[]>([]); const[trend,setTrend]=useState<Trend|null>(null); const[running,setRunning]=useState(false); const[progress,setProgress]=useState(0); const[error,setError]=useState(''); const[projects,setProjects]=useState<any[]>([]); const[saveMsg,setSaveMsg]=useState('');
 function add(fs:FileList|File[]){const valid=Array.from(fs).filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)).slice(0,50-imgs.length);setImgs(a=>[...a,...valid.map(file=>({id:crypto.randomUUID(),file,url:URL.createObjectURL(file)}))]);}
 function del(id:string){setImgs(a=>{const x=a.find(v=>v.id===id);if(x)URL.revokeObjectURL(x.url);return a.filter(v=>v.id!==id)})}
 async function dataUrl(file:File){return await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
 async function loadProjects(){try{const r=await fetch('/api/projects');const d=await r.json();if(r.ok&&d.projects)setProjects(d.projects)}catch{}}
 async function saveProject(){if(!results.length){setSaveMsg('Run an analysis first.');return}setSaveMsg('Saving…');try{const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:`Creative Analysis ${new Date().toLocaleString()}`,metadata:{target,level,imageCount:imgs.length,results}})});const d=await r.json();setSaveMsg(r.ok?`Saved project: ${d.project?.name||'Project'}`:(d.error||'Save failed.'));if(r.ok)loadProjects()}catch{setSaveMsg('Save failed. Check Supabase configuration and login.')}}
 async function exportXlsx(){if(!results.length)return;const r=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({results})});if(!r.ok){setError('Excel export failed.');return}const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='creative-results.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function analyze(){if(!imgs.length){setMsg('Upload at least one image first.');return} setRunning(true);setError('');setMsg('AI analysis চলছে…');setResults([]);setTrend(null);setProgress(0); const out:AnalysisResult[]=[];
   for(let i=0;i<imgs.length;i++){try{const imageDataUrl=await dataUrl(imgs[i].file);const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageDataUrl,target,level,count,imageId:imgs[i].id})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Analysis failed');out.push(data);setResults([...out]);}catch(e:any){setError(`Image #${i+1}: ${e.message}`)}setProgress(Math.round(((i+1)/imgs.length)*100));}
   if(out.length){try{const r=await fetch('/api/trends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analyses:out})});const t=await r.json();if(r.ok)setTrend(t)}catch{} setMsg(`Completed ${out.length}/${imgs.length} image analyses.`)} else setMsg('No image could be analyzed. Check your server API key and connection.'); setRunning(false);
 }
 const opportunities=trend?.opportunities ?? []; const allPrompts=results.flatMap(r=>r.prompts||[]); const preview=allPrompts[0]?.prompt || `Create a fresh, commercially useful visual concept inspired only by broad characteristics of the reference. Make substantial changes to composition, viewpoint, environment, lighting, supporting elements and distinctive visual features. Target: ${target}. Differentiation: ${level}.`;
 function exportTxt(){const text=results.map((r,i)=>`IMAGE ${i+1}\nSubject: ${r.analysis.subject}\nStyle: ${r.analysis.visualStyle}\nColors: ${r.analysis.colorPalette.join(', ')}\n\n${(r.prompts||[]).map((p,j)=>`PROMPT ${j+1}: ${p.title}\n${p.prompt}\nAvoid: ${p.negativeGuidance.join(', ')}`).join('\n\n')}`).join('\n\n---\n\n');downloadBlob(text,'creative-results.txt','text/plain')}
 function exportCsv(){const rows=[['Image','Prompt Title','Prompt','Negative Guidance']];results.forEach((r,i)=>(r.prompts||[]).forEach(p=>rows.push([String(i+1),p.title,p.prompt,p.negativeGuidance.join('; ')])));downloadBlob(rows.map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'creative-results.csv','text/csv')}
 function downloadBlob(text:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 const metric=(title:string,items:any[])=> <div className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="text-xs text-white/40">{title}</div>{items?.length?<div className="mt-3 space-y-2">{items.slice(0,5).map((x:any)=><div key={x.label} className="flex justify-between gap-3 text-xs"><span className="truncate text-white/70">{x.label}</span><b className="text-white/40">{x.count}</b></div>)}</div>:<div className="mt-3 text-sm text-white/30">Awaiting AI analysis</div>}</div>;
 useEffect(()=>{loadProjects()},[]);
 return <main className="min-h-screen"><header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-indigo-500"><Sparkles size={20}/></div><div><b>AI Creative Inspiration</b><div className="text-xs text-white/40">& Differentiation Tool</div></div></div><div className="flex items-center gap-2"><a href="/login" className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/60">Sign in</a><span className="rounded-full bg-white/5 px-3 py-2 text-xs text-white/50">AI Analysis • Trend Engine</span></div></div></header>
 <section className="mx-auto max-w-7xl px-6 py-12"><h1 className="max-w-4xl text-4xl font-bold sm:text-6xl">Turn references into <span className="text-violet-300">new creative directions.</span></h1><p className="mt-4 max-w-2xl text-white/50">Upload up to 50 images. Analyze visual patterns, generate differentiated prompts, and discover recurring creative trends.</p>
 <div className="mt-10 grid gap-6 lg:grid-cols-[1.5fr_.8fr]"><section className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();add(e.dataTransfer.files)}} className="grid min-h-64 place-items-center rounded-2xl border-2 border-dashed border-white/10 bg-black/10 p-8 text-center"><div><UploadCloud className="mx-auto text-violet-300" size={42}/><h2 className="mt-4 text-lg font-semibold">Drop reference images here</h2><p className="mt-2 text-sm text-white/40">JPG, PNG, WEBP • up to 50</p><button onClick={()=>ref.current?.click()} className="mt-5 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black">Select Images</button><input ref={ref} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files&&add(e.target.files)}/></div></div><div className="mt-4 flex items-center justify-between text-sm text-white/50"><span>{imgs.length}/50 uploaded</span>{running&&<span>{progress}%</span>}</div>{running&&<div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-violet-500 transition-all" style={{width:`${progress}%`}}/></div>}{imgs.length>0&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4 md:grid-cols-5">{imgs.map((x,i)=><div className="group relative aspect-square overflow-hidden rounded-xl border border-white/10" key={x.id}><img src={x.url} className="h-full w-full object-cover"/><span className="absolute bottom-0 left-0 bg-black/70 px-2 py-1 text-[10px]">#{i+1}</span><button disabled={running} onClick={()=>del(x.id)} className="absolute right-2 top-2 rounded bg-black/70 p-1 opacity-0 group-hover:opacity-100"><X size={14}/></button></div>)}{imgs.length<50&&<button disabled={running} onClick={()=>ref.current?.click()} className="grid aspect-square place-items-center rounded-xl border border-dashed border-white/10"><Plus/></button>}</div>}</section>
 <aside className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex gap-2 text-sm font-semibold"><Layers3 size={18}/> Output settings</div><label className="mt-7 block text-xs text-white/40">Target</label><select value={target} onChange={e=>setTarget(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3"><option>ChatGPT Image</option><option>Midjourney</option><option>Flux</option><option>Stable Diffusion</option></select><label className="mt-6 block text-xs text-white/40">Variations</label><div className="mt-2 flex items-center justify-between rounded-xl border border-white/10 p-2"><button onClick={()=>setCount(Math.max(1,count-1))}><Minus/></button><b>{count}</b><button onClick={()=>setCount(Math.min(10,count+1))}><Plus/></button></div><label className="mt-6 block text-xs text-white/40">Differentiation</label><div className="mt-2 grid grid-cols-3 gap-2">{['Low','Medium','High'].map(x=><button key={x} onClick={()=>setLevel(x)} className={`rounded-xl border p-3 text-xs ${level===x?'border-violet-400/50 bg-violet-400/10':'border-white/10'}`}>{x}</button>)}</div><button disabled={running} onClick={analyze} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-500 to-indigo-500 p-3.5 text-sm font-semibold disabled:opacity-50">{running?<Loader2 className="animate-spin" size={17}/>:<Sparkles size={17}/>} {running?'Analyzing…':'Analyze & Generate'}</button>{msg&&<p className="mt-4 rounded-xl bg-white/5 p-3 text-xs leading-5 text-white/55">{msg}</p>}{error&&<p className="mt-3 flex gap-2 rounded-xl bg-red-400/10 p-3 text-xs leading-5 text-red-200"><AlertCircle size={15}/>{error}</p>}</aside></div>
 <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-2 text-sm font-semibold"><BarChart3 size={18}/> Visual Data Analysis</div><p className="mt-2 text-sm text-white/45">Aggregated from the images successfully analyzed in this project.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{metric('Top visual themes',trend?.themes||[])}{metric('Style clusters',trend?.styles||[])}{metric('Color trends',trend?.colors||[])}{metric('Composition patterns',trend?.compositions||[])}{metric('Mood signals',trend?.moods||[])}</div>{opportunities.length>0&&<div className="mt-4 rounded-2xl border border-violet-400/20 bg-violet-400/5 p-4"><div className="text-xs text-violet-200">Creative opportunity signals</div><ul className="mt-2 list-disc pl-5 text-sm leading-6 text-white/65">{opportunities.map(x=><li key={x}>{x}</li>)}</ul></div>}</section>
 <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><b>Generated Prompt Results</b><p className="mt-1 text-xs text-white/40">Each result is designed to be meaningfully differentiated from its reference.</p></div><div className="flex gap-2">{results.length>0&&<><button onClick={exportTxt} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs"><Download size={14}/>TXT</button><button onClick={exportCsv} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs"><Download size={14}/>CSV</button><button onClick={exportXlsx} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs"><Download size={14}/>Excel</button><button onClick={saveProject} className="flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-400/5 px-3 py-2 text-xs"><Save size={14}/>Save</button></>}</div></div>{results.length? <div className="mt-5 space-y-5">{results.map((r,i)=><div key={r.imageId} className="rounded-2xl border border-white/10 bg-black/15 p-5"><div className="flex justify-between gap-3"><div><div className="text-xs text-white/40">Image #{i+1}</div><h3 className="mt-1 font-semibold">{r.analysis.subject}</h3></div><span className="text-xs text-white/35">{r.analysis.visualStyle}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{r.prompts.map((p,j)=><div key={j} className="rounded-xl border border-white/10 p-4"><div className="text-xs font-semibold text-violet-200">{p.title}</div><p className="mt-2 text-sm leading-6 text-white/65">{p.prompt}</p><div className="mt-3 text-[11px] text-white/35">Avoid: {p.negativeGuidance.join(', ')}</div><button onClick={async()=>{await navigator.clipboard?.writeText(p.prompt)}} className="mt-3 flex items-center gap-2 text-xs text-white/50"><Copy size={13}/>Copy prompt</button></div>)}</div></div>)}</div>:<div className="mt-5 rounded-2xl bg-black/20 p-5 text-sm leading-7 text-white/40">Run an analysis to populate real prompt results here.</div>}</section>
 {saveMsg&&<p className="mt-3 text-xs text-white/45">{saveMsg}</p>}
 <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-2 text-sm font-semibold"><History size={18}/> Recent Projects</div>{projects.length?<div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{projects.slice(0,8).map(p=><div key={p.id} className="rounded-xl border border-white/10 p-3 text-xs"><div className="font-medium text-white/75 truncate">{p.name}</div><div className="mt-1 text-white/30">{new Date(p.updated_at||p.created_at).toLocaleString()}</div></div>)}</div>:<p className="mt-3 text-xs text-white/35">Configure Supabase and sign in to persist projects and history.</p>}</section>
 <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center justify-between gap-4"><div><b>Prompt Preview</b><p className="mt-1 text-xs text-white/40">A quick copyable preview of the first generated direction.</p></div><button onClick={async()=>{await navigator.clipboard?.writeText(preview);setCopied(true);setTimeout(()=>setCopied(false),1200)}} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-xs">{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':'Copy'}</button></div><div className="mt-4 rounded-2xl bg-black/20 p-5 text-sm leading-7 text-white/60">{preview}</div></section>
 <p className="mt-6 text-xs leading-5 text-white/30">Important: differentiation reduces direct replication risk, but no AI workflow can guarantee copyright clearance, trademark safety, originality, or acceptance by a stock/POD marketplace. Review outputs before commercial use.</p>
 </section></main>
}
