'use client';
import {useEffect,useState} from 'react';
import {BarChart3,FolderOpen,CreditCard,ArrowRight,RefreshCw} from 'lucide-react';
export default function Dashboard(){const [projects,setProjects]=useState<any[]>([]);const[credits,setCredits]=useState<any>(null);const[loading,setLoading]=useState(true);const[err,setErr]=useState('');
 async function load(){setLoading(true);const [p,c]=await Promise.all([fetch('/api/projects'),fetch('/api/credits')]);const pd=await p.json(),cd=await c.json();if(p.ok)setProjects(pd.projects||[]);if(c.ok)setCredits(cd.credits);else setErr(cd.error||'Sign in required');setLoading(false)} useEffect(()=>{load()},[]);
 return <main className="mx-auto max-w-7xl px-6 py-10"><div className="flex items-center justify-between"><div><p className="text-sm text-violet-300">Workspace</p><h1 className="mt-1 text-3xl font-semibold">Your creative dashboard</h1><p className="mt-2 text-sm text-white/45">Projects, credits and your latest analysis history.</p></div><button onClick={load} className="rounded-xl border border-white/10 p-3"><RefreshCw size={16}/></button></div>{err&&<div className="mt-6 rounded-xl bg-amber-500/10 p-4 text-sm text-amber-200">{err}. <a href="/login" className="underline">Sign in</a></div>}
 <div className="mt-8 grid gap-4 md:grid-cols-3"><Card icon={<CreditCard/>} title="Credits" value={credits?.credits??'—'} note={credits?.plan?`Plan: ${credits.plan}`:'Not connected'}/><Card icon={<FolderOpen/>} title="Projects" value={projects.length} note="Saved creative work"/><Card icon={<BarChart3/>} title="Usage" value={credits?.credits_used??'—'} note="Credits used"/></div>
 <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent projects</h2><a href="/" className="flex items-center gap-2 text-xs text-violet-300">New analysis <ArrowRight size={14}/></a></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{projects.map(p=><a key={p.id} href={`/projects/${p.id}`} className="rounded-xl border border-white/10 p-4 hover:bg-white/5"><div className="font-medium">{p.name}</div><div className="mt-2 text-xs text-white/35">{new Date(p.updated_at||p.created_at).toLocaleString()}</div></a>)}{!loading&&!projects.length&&<p className="text-sm text-white/35">No saved projects yet.</p>}</div></section></main>}
function Card({icon,title,value,note}:{icon:any;title:string;value:any;note:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="text-white/45">{icon}</div><div className="mt-4 text-3xl font-semibold">{value}</div><div className="mt-1 text-sm">{title}</div><div className="mt-1 text-xs text-white/35">{note}</div></div>}
